#ifndef DEVICETREE_GENERATED_SAMPLE_H
#define DEVICETREE_GENERATED_SAMPLE_H

/* Sample node macros exercising the grammar additions. */
#define DT_N_S_soc_S_uart_40002000_PATH "/soc/uart@40002000"
#define DT_N_S_soc_S_uart_40002000_FULL_NAME "uart@40002000"
#define DT_N_S_soc_S_uart_40002000_FULL_NAME_UNQUOTED uart@40002000
#define DT_N_S_soc_S_uart_40002000_FULL_NAME_TOKEN uart_40002000
#define DT_N_S_soc_S_uart_40002000_FULL_NAME_UPPER_TOKEN UART_40002000
#define DT_N_S_soc_S_uart_40002000_FOREACH_ANCESTOR(fn) \
fn(DT_N_S_soc) fn(DT_N)
#define DT_N_S_soc_S_uart_40002000_HASH 0x12345678
#define DT_N_S_soc_S_uart_40002000_ORD_STR_SORTABLE 00042
#define DT_N_S_soc_S_uart_40002000_REQUIRES_ORDS {0, 1}
#define DT_N_S_soc_S_uart_40002000_SUPPORTS_ORDS {2}

/* Chosen node helpers. */
#define DT_CHOSEN_zephyr_console DT_N_S_soc_S_uart_40002000
#define DT_CHOSEN_zephyr_console_EXISTS 1

/* Helper macros generated by gen_defines.py. */
#define DT_DEBRACKET_INTERNAL(...) __VA_ARGS__
#define DT_FOREACH_HELPER(fn) fn(DT_N)
#define DT_FOREACH_VARGS_HELPER(fn, ...) fn(DT_N, __VA_ARGS__)
#define DT_FOREACH_OKAY_HELPER(fn) fn(DT_N)
#define DT_FOREACH_OKAY_VARGS_HELPER(fn, ...) fn(DT_N, __VA_ARGS__)

#endif /* DEVICETREE_GENERATED_SAMPLE_H */
