// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
#ifndef __BINDINGS_BLINK_H
#define __BINDINGS_BLINK_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Imported Functions from `zephyr:led/driver`
extern int32_t zephyr_led_driver_configure(void);
extern int32_t zephyr_led_driver_set(bool value);
extern int32_t zephyr_led_driver_sleep_ms(uint32_t ms);

// Exported Functions from `blink`
void exports_blink_run(void);

#ifdef __cplusplus
}
#endif
#endif
