// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
#include "blink.h"
#include <stdlib.h>

// Imported Functions from `zephyr:led/driver`

__attribute__((__import_module__("zephyr:led/driver"), __import_name__("configure")))
extern int32_t __wasm_import_zephyr_led_driver_configure(void);

__attribute__((__import_module__("zephyr:led/driver"), __import_name__("set")))
extern int32_t __wasm_import_zephyr_led_driver_set(int32_t);

__attribute__((__import_module__("zephyr:led/driver"), __import_name__("sleep-ms")))
extern int32_t __wasm_import_zephyr_led_driver_sleep_ms(int32_t);

// Exported Functions from `blink`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

int32_t zephyr_led_driver_configure(void) {
  int32_t ret = __wasm_import_zephyr_led_driver_configure();
  return ret;
}

int32_t zephyr_led_driver_set(bool value) {
  int32_t ret = __wasm_import_zephyr_led_driver_set(value);
  return ret;
}

int32_t zephyr_led_driver_sleep_ms(uint32_t ms) {
  int32_t ret = __wasm_import_zephyr_led_driver_sleep_ms((int32_t) (ms));
  return ret;
}

__attribute__((__export_name__("run")))
void __wasm_export_exports_blink_run(void) {
  exports_blink_run();
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_blink(void);
__attribute__((used))
void __component_type_object_force_link_blink_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_blink();
}
